"""Reference suite for CSCV/PBO. Golden values pin the implementation."""

import numpy as np
import pytest

from alpha_forge.gates.pbo import cscv_pbo

GOLDEN = {}


def test_pure_noise_pbo_near_half():
    # a single draw's PBO has high variance (CSCV splits share blocks), but
    # the estimator is unbiased: the MEAN over independent draws sits at ~0.5
    vals = []
    for seed in range(8):
        rng = np.random.default_rng(seed)
        m = rng.normal(0, 0.01, size=(640, 20))
        out = cscv_pbo(m)
        assert out["n_splits"] == 12870
        vals.append(out["pbo"])
    assert 0.38 < float(np.mean(vals)) < 0.60


def test_true_edge_pbo_low():
    rng = np.random.default_rng(1)
    m = rng.normal(0, 0.01, size=(640, 20))
    m[:, 3] += 0.004  # one genuinely superior config
    out = cscv_pbo(m)
    assert out["pbo"] < 0.10


def test_overfit_pbo_high():
    # configs identical in distribution but IS selection chases noise:
    # antithetic pairs make the IS winner systematically mediocre OOS
    rng = np.random.default_rng(2)
    base = rng.normal(0, 0.01, size=(640, 10))
    m = np.column_stack([base, -base])  # winner IS is loser in mirrored blocks
    out = cscv_pbo(m)
    assert out["pbo"] > 0.4


def test_input_validation():
    with pytest.raises(ValueError):
        cscv_pbo(np.zeros((10, 5)))  # too few periods for 16 blocks
    with pytest.raises(ValueError):
        cscv_pbo(np.zeros((100, 1)))  # single config


def test_golden_value_reference_implementation():
    rng = np.random.default_rng(123)
    m = rng.normal(0.0002, 0.01, size=(320, 16))
    out = cscv_pbo(m)
    assert out["pbo"] == pytest.approx(GOLDEN["pbo"], abs=1e-12)
    assert out["lambda_mean"] == pytest.approx(GOLDEN["lambda_mean"], abs=1e-9)


GOLDEN.update(
    {
        # generated by scripts/gen_goldens.py from the reference implementation
        "pbo": 0.3662004662004662,
        "lambda_mean": 0.41869168388793687,
    }
)
