"""Reference suite for the DSR implementation.

The GOLDEN values pin this implementation's outputs on fixed inputs; any port
(Rust, Polars, whatever) must reproduce them to 1e-9 before it may replace
this module (Operating Rules). Invariant tests check the math behaves like
the paper says it should.
"""

import numpy as np
import pytest

from alpha_forge.gates.dsr import (
    deflated_sharpe_ratio,
    expected_max_sharpe,
    probabilistic_sharpe_ratio,
    sharpe_ratio,
)

GOLDEN = {}  # filled below, generated once from the reference implementation


def test_sharpe_basic():
    r = np.array([0.01, -0.02, 0.03, 0.01, -0.01])
    assert sharpe_ratio(r) == pytest.approx(r.mean() / r.std(ddof=1), abs=1e-15)


def test_psr_at_benchmark_is_half():
    # observed SR equal to the benchmark => 50/50 by construction
    assert probabilistic_sharpe_ratio(0.3, 0.3, 100, 0.0, 3.0) == pytest.approx(0.5, abs=1e-12)


def test_psr_monotone_in_track_length():
    p_short = probabilistic_sharpe_ratio(0.2, 0.0, 24, 0.0, 3.0)
    p_long = probabilistic_sharpe_ratio(0.2, 0.0, 240, 0.0, 3.0)
    assert p_long > p_short


def test_psr_penalizes_bad_higher_moments():
    clean = probabilistic_sharpe_ratio(0.2, 0.0, 100, 0.0, 3.0)
    ugly = probabilistic_sharpe_ratio(0.2, 0.0, 100, -1.5, 8.0)
    assert ugly < clean


def test_expected_max_sharpe_grows_with_trials():
    v = 0.05
    vals = [expected_max_sharpe(n, v) for n in (1, 10, 100, 1000)]
    assert vals[0] == 0.0
    assert vals[1] < vals[2] < vals[3]


def test_expected_max_sharpe_against_monte_carlo():
    # E[max of N iid Normal(0, sqrt(v))] vs the paper's approximation
    rng = np.random.default_rng(7)
    n, v = 200, 0.04
    sim = rng.normal(0.0, np.sqrt(v), size=(20000, n)).max(axis=1).mean()
    approx = expected_max_sharpe(n, v)
    assert approx == pytest.approx(sim, rel=0.02)


def test_dsr_deflates_with_trial_count():
    rng = np.random.default_rng(3)
    r = rng.normal(0.001, 0.01, 500)
    d1 = deflated_sharpe_ratio(r, n_trials=1, var_trial_sr=0.02)
    d100 = deflated_sharpe_ratio(r, n_trials=100, var_trial_sr=0.02)
    assert d100["dsr_probability"] < d1["dsr_probability"]
    assert d100["sr0_benchmark"] > 0.0 == d1["sr0_benchmark"]


def test_golden_values_reference_implementation():
    """Ports must reproduce these to 1e-9 (fixed seed, fixed inputs)."""
    rng = np.random.default_rng(42)
    r = rng.normal(0.0008, 0.012, 756)
    out = deflated_sharpe_ratio(r, n_trials=50, var_trial_sr=0.01)
    assert out["sr_per_period"] == pytest.approx(GOLDEN["sr_per_period"], abs=1e-9)
    assert out["sr0_benchmark"] == pytest.approx(GOLDEN["sr0_benchmark"], abs=1e-9)
    assert out["dsr_probability"] == pytest.approx(GOLDEN["dsr_probability"], abs=1e-9)


GOLDEN.update(
    {
        # generated by scripts/gen_goldens.py from the reference implementation
        "sr_per_period": 0.026886963652523264,
        "sr0_benchmark": 0.22763030934203485,
        "dsr_probability": 1.721263616366555e-08,
    }
)
