"""FINDINGS.md — regenerated by every daily run.

Leads with the four numbers the owner decides on. Numbers that cannot yet be
computed from live data say so explicitly — an honest N/A beats a marketing
figure, and a single-point projection is never printed where a distribution
is required.
"""

from __future__ import annotations

from datetime import datetime, timezone

import polars as pl

from alpha_forge.config import REPO_ROOT
from alpha_forge.ledger import Ledger


def render_findings(
    ledger: Ledger,
    window_counts: pl.DataFrame | None,
    hits: pl.DataFrame | None,
    gate_reports: list[dict],
    dataset_note: str,
    replacement_rate_note: str,
    extra_sections: list[str] | None = None,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    trials = ledger.trial_count()
    graduated = [g for g in gate_reports if g.get("verdict") == "PASS"]

    lines = [
        f"# ALPHA FORGE — FINDINGS (regenerated {now})",
        "",
        "## The four numbers",
        "",
    ]

    # 1 — book growth rate
    lines += [
        "**1. Sustainable net compounded growth rate of the book:** "
        + (
            "N/A — the strategy book is EMPTY. No strategy has yet completed "
            "all Section-4 gates plus live reconciliation; a growth rate quoted "
            "from backtest data alone would be exactly the kind of number this "
            "system exists to refuse to print."
            if not graduated
            else "see candidate table below — gate-passing candidates exist but "
            "none has the 60-day live calibration record required before a "
            "book-level growth rate (with CI from live data) is quotable."
        ),
        "",
        f"**2. Pipeline replacement rate:** {replacement_rate_note}",
        "",
        "**3. Capacity ceiling of current book:** N/A — empty book; capacity "
        "estimation (Agent 8a) activates on first graduation.",
        "",
        "**4. Projected wealth fan chart:** deferred — a fan chart requires a "
        "validated growth-rate distribution from live calibration data, which "
        "does not exist yet. No single-point projection is printed in its place.",
        "",
        f"**Cumulative ledgered trial count: {trials}** (feeds every DSR "
        "computation; persists across sessions and reruns)",
        "",
        f"**Killed candidate strategies: {len(ledger.killed_strategies())} "
        "(distinct)** — trials and kills are different populations: a trial "
        "is one evaluated configuration, a kill is a strategy-level verdict. "
        "Neither number implies the other.",
        "",
        f"_Data: {dataset_note}_",
        "",
    ]

    if gate_reports:
        lines += ["## Section-4 gate outcomes", ""]
        for g in gate_reports:
            lines.append(f"### {g['strategy_id']} — verdict: **{g['verdict']}**")
            for r in g.get("reasons", []):
                lines.append(f"- {r}")
            checks = g.get("checks", {})
            nvg = checks.get("net_vs_gross", {})
            if nvg:
                lines.append(
                    f"- gross total return {nvg['gross_total_return']:+.1%} / "
                    f"**net {nvg['net_total_return']:+.1%}** (gate 6: never shown apart)"
                )
            dsr = checks.get("dsr", {})
            if dsr:
                lines.append(
                    f"- DSR probability {dsr['dsr_probability']:.4f} at N={dsr['n_trials']} trials"
                )
            pbo = checks.get("pbo", {})
            if pbo:
                lines.append(f"- PBO {pbo['pbo']:.3f} over {pbo['n_splits']} CSCV splits")
            nb = checks.get("null_baseline", {})
            if nb:
                lines.append(
                    f"- null baseline: net metric {nb['strategy_net_metric']:.4f} vs "
                    f"null p95 {nb['null_p95']:.4f} ({nb['n_draws']} matched draws)"
                )
            lines.append("")

    lines += ["## Historical N-x path catalog (Pathfinder, Agent 2)", ""]
    if window_counts is not None and window_counts.height > 0:
        summary = (
            window_counts.group_by("n_multiple")
            .agg(
                pl.col("distinct_symbols_with_path").sum().alias("symbol_window_hits"),
                pl.len().alias("windows_with_any_path"),
            )
            .sort("n_multiple")
        )
        lines.append("| N-x | symbol-window hits | windows with ≥1 path |")
        lines.append("|-----|-------------------:|---------------------:|")
        for row in summary.iter_rows(named=True):
            lines.append(
                f"| {row['n_multiple']}x | {row['symbol_window_hits']} | {row['windows_with_any_path']} |"
            )
        lines.append("")
        lines.append(
            f"Full catalog with ex-ante fingerprints: `data/store/path_hits.parquet` "
            f"({0 if hits is None else hits.height} hits). Sequences: 0 — composed only "
            "from gate-passing setups, and the graduated book is empty (by design, "
            "not omission)."
        )
    else:
        lines.append("No qualifying N-x paths in the current sample (see dataset note).")
    for section in extra_sections or []:
        lines += ["", section]

    lines += [
        "",
        "## Standing disclosures",
        "",
        "- **Status ceiling: PIPELINE_PROOF_ONLY.** No candidate may hold "
        "VALIDATED, GRADUATED, or EXECUTABLE status until point-in-time "
        "survivorship-free data is installed — enforced in code (the ledger "
        "refuses GRADUATION entries), not by convention.",
        "- Universe is built from CURRENT listings (survivorship-biased); every "
        "result above carries gate-7 flag until a survivorship-free vendor is wired. "
        "The observed anti-selection in event candidates (strategies lose where "
        "matched random entries profit) is HYPOTHESIZED to be caused by this "
        "bias — causation is untested until the same research runs on "
        "point-in-time data that includes delisted securities.",
        "- Path counts from the research sample extrapolate to the full universe "
        "only under the documented uniform-sampling assumption.",
        "- Options/futures agents are in DESIGN mode (no keys present): they emit "
        "queries, never synthetic backtests.",
    ]
    return "\n".join(lines) + "\n"


def write_findings(content: str) -> None:
    (REPO_ROOT / "FINDINGS.md").write_text(content)
